# Homework Assignment 3

You may use whatever IDEs Platforms / text editors you like, but you mustsubmit your responses and source code files (Jupyter notebooks are considered as such) on iCollege.

Note: Please refer to the Jupyter notebooks created in class. They provide useful hints for solving the following problems. In the submitted Jupyter notebook(s), your code cells’ output (if any) should be visible without executing the notebook

You may use whatever IDEs Platforms / text editors you like, but you mustsubmit your responses and source code files (Jupyter notebooks are considered as such) on iCollege.

Note: Please refer to the Jupyter notebooks created in class. They provide useful hints for solving the following problems. In the submitted Jupyter notebook(s), your code cells’ output (if any) should be visible without executing the notebook

In [1]:
import pandas as pd
import numpy as np
import sqlite3
import regex as re
from tqdm.auto import tqdm
from collections import Counter
from spacy.lang.en.stop_words import STOP_WORDS

/usr/local/lib/python3.8/dist-packages/torch/cuda/__init__.py:497: UserWarning: Can't initialize NVML
  warnings.warn("Can't initialize NVML")


(a) (1 point) Prove that the database file has been properly loaded by showing (output requested) that the table “wiki_articles_extended” exists and the pandas dataframe “df” contains the expected columns “title”, “text”, “name”, “url”, and “nouns” (along with many other columns) as well as 60 rows for the respective Wikipedia texts/documents. 

In [4]:
con = sqlite3.connect("wiki-articles-extended.db")

df = pd.read_sql_query("SELECT * from wiki_articles_extended", con)
#con.close()
df 

index                                      title  \
0       0                                 Abuse case   
1       1                       Application security   
2       2                  Asset (computer security)   
3       3                                Attack tree   
4       4                           Automated threat   
5       5                           Browser security   
6       6                            Buffer overflow   
7       7                           Code refactoring   
8       8                      Coding best practices   
9       9           Computer emergency response team   
10     10                 Computer security software   
11     11                  Countermeasure (computer)   
12     12                       Cross-site scripting   
13     13                       Cyber threat hunting   
14     14                                Cyberattack   
15     15                              Data security   
16     16                          Database security   
17     17               Defense in depth (computing)   
18     18                      Defensive programming   
19     19                                     DevOps   
20     20              DREAD (risk assessment model)   
21     21       Dynamic application security testing   
22     22                Exploit (computer security)   
23     23            Information security management   
24     24                       Information security   
25     25                          Internet security   
26     26                                    IT risk   
27     27                                    Malware   
28     28                                Misuse case   
29     29                            Mobile security   
30     30                     Obfuscation (software)   
31     31                                      OWASP   
32     32                           Penetration test   
33     33                    Risk factor (computing)   
34     34                Sandbox (computer security)   
35     35                          Secure by default   
36     36                           Secure by design   
37     37                               Security bug   
38     38                          Security controls   
39     39                       Security engineering   
40     40  Security information and event management   
41     41                           Security testing   
42     42          Security-focused operating system   
43     43                         Shift-left testing   
44     44              Social engineering (security)   
45     45                               Software bug   
46     46               Software development process   
47     47              Software development security   
48     48                           Software quality   
49     49                Software security assurance   
50     50                           Software testing   
51     51                              SQL injection   
52     52        Static application security testing   
53     53                          STRIDE (security)   
54     54                             System testing   
55     55             Systems development life cycle   
56     56                               Threat model   
57     57                  Vulnerability (computing)   
58     58                      Vulnerability scanner   
59     59                   Web application firewall   

                                                 text  \
0   From Wikipedia, the free encyclopedia\n\n\nAbu...   
1   From Wikipedia, the free encyclopedia\n\n\nMea...   
2   From Wikipedia, the free encyclopedia\n\n\nDat...   
3   From Wikipedia, the free encyclopedia\n\n\nCon...   
4   From Wikipedia, the free encyclopedia\n\n\nPar...   
5   From Wikipedia, the free encyclopedia\n\n\nApp...   
6   From Wikipedia, the free encyclopedia\n\n\nAno...   
7   From Wikipedia, the free encyclopedia\n\n\nRes...   
8   From Wikipedia, the free encyclopedia\n\n\nThi...   
9   From Wikipedi

(b) (2 points) Extract the most common 7500 nouns from all the 60 Wikipedia texts. These tokens must be in lower case and have a length of at least 1. Also, they cannot be stop words. For this purpose, please use the code fragments provided. Afterwards, the object “nouns” will map from a token to its overall frequency. The list “voc” contains the strings of tokens extracted, sorted in descending order of their frequency of occurrence (the token at the largest index position 7499 will be the least frequent one). Thus, this list can be used to find an index for a specific token. For instance, the index of token “information” in this list could be 3, found by calling voc.index("information") . Show that the list “voc” contains 7500 tokens and that there are no 
tokens with a frequency of 0 in it (the last element in it must appear at least 1 time).

In [5]:
def single_words(df, field):
    return [w.lower() for words in df[field] for w in re.split(r'\||\#', words) if len(w)>1]

In [6]:
nouns = Counter(single_words(df, "nouns"))
for w in STOP_WORDS:
    nouns[w] = 0
    
voc = [w for w, freq in nouns.most_common(7500)]
#voc.index("information")

assert len(voc) == 7500   # assert is showing that the list “voc” contains 7500 tokens
assert min(nouns[word] for word in voc) > 0 # assert shows that there are no tokens with a frequency of 0 in it (the last element in it must appear at least 1 time).

### Tasks 1a and 1b

(c) (15 points) Create a co-occurrence matrix (named e.g. “coocc_matrix”) using a 2-dimensional Numpy array that has a shape of (7500x7500). Each element in this matrix should be initialized to 0 and will count how often a token i appears together with a token j in df[“nouns”] using a cooccurrence window of 5. The tokens to be extracted (in lower case, no stop words) from df[“nouns”] must appear in the previously obtained list “voc”. For instance, the element at (3, 0) could be accessed by “coocc_matrix[0][3]”. As an undirected co-occurrence graph is generated this way, the value of “coocc_matrix[0][3]” must match that of “coocc_matrix[3][0]”. The mentioned indices 0 and 3 can be obtained by calling voc.index("information") and 
voc.index("security"). 

Note: Co-occurrences of a token with itself in the co-occurrence window should be counted.

In [7]:
from collections import defaultdict
c = defaultdict(lambda: Counter())


coocc_matrix = np.zeros((len(voc), len(voc))) # numpy np.zeros is initializing co-occurrence matrix with zeros with shape of (7500x7500)

window = 5 # The initialization of window size to 5
skip = (window - 1) // 2
for doc in tqdm(df["nouns"]):
   
    tokens = [w for w in re.split(r'\||\#', doc) if w not in STOP_WORDS]  # The removal of stop words
    for i, w in enumerate(tokens):
        if w in voc:
            for j in range(max(0, i-skip), i):
                if tokens[j] in voc:
                    c[w][tokens[j]] += 1
            for j in range(i+1, min(i+1+skip, len(tokens))):
                if tokens[j] in voc:
                    c[w][tokens[j]] += 1


for key, counter in c.items(): # The statement Iterating over each key-value pair in the dictionary
    i = voc.index(key)
    for k, v in counter.items():
        j = voc.index(k)
        coocc_matrix[i][j] = v
        coocc_matrix[j][i] = v  # Since it's an undirected graph, assign the same value to both positions


print(coocc_matrix) # Print the resulting co-occurrence matrix        


print(coocc_matrix[0][3]) 
print(coocc_matrix[3][0]) 
print(coocc_matrix[voc.index("security")][voc.index("information")]) 
print(coocc_matrix[voc.index("information")][voc.index("security")]) 

  0%|          | 0/60 [00:00<?, ?it/s]

[[436. 189. 178. ...   0.   0.   0.]
 [189. 166.  99. ...   0.   0.   0.]
 [178.  99. 176. ...   0.   0.   0.]
 ...
 [  0.   0.   0. ...   0.   1.   1.]
 [  0.   0.   0. ...   1.   0.   1.]
 [  0.   0.   0. ...   1.   1.   0.]]
322.0
322.0
322.0
322.0


(d) (3 points) For all indices i and j, prove that the elements “coocc_matrix[i][j]” and “coocc_matrix[j][i]” have the same values.

In [8]:
print(coocc_matrix[0][3]) 
print(coocc_matrix[3][0]) 
assert coocc_matrix[0][3] == coocc_matrix[3][0] # assert will raises an exception if the condition is not met 
                                                # Because this assert is not raising an execption hence “coocc_matrix[i][j]” and “coocc_matrix[j][i]” have the same values.


print(coocc_matrix[voc.index("security")][voc.index("information")]) 
print(coocc_matrix[voc.index("information")][voc.index("security")]) 
assert coocc_matrix[voc.index("security")][voc.index("information")] == coocc_matrix[voc.index("information")][voc.index("security")]

322.0
322.0
322.0
322.0


# Co-occurrence analysis (main homework)


(2) (7 points) Extend the Jupyter notebook (in Python) created in 1) by providing solutions to the following tasks:

(a) Using the basic PageRank algorithm (not the extended variant) applied to a stochastic matrix derived from the co-occurrence matrix obtained in 1c), output the ten most important 
keywords/tokens of “voc” sorted in descending order by their PageRank values.

Note: For this purpose, you can use the function “pagerank()” from the Python-example under https://en.wikipedia.org/wiki/PageRank , which computes the PageRank scores using the power 
method described in this Wikipedia-article. In order to be able to do so, you must first transform the obtained co-occurrence matrix into a stochastic matrix by e.g. calling 
stochastic_matrix = coocc_matrix / (coocc_matrix.sum(axis=0, keepdims=True)+0.001). Then, the mentioned function “pagerank” can be called by v = pagerank(stochastic_matrix) .

In [10]:
stochastic_matrix = coocc_matrix / (coocc_matrix.sum(axis=0, keepdims=True)+0.001) # Compute the stochastic matrix

def pagerank(M, num_iterations=100, d=0.85): # Implement the PageRank algorithm
    N = M.shape[1]
    v = np.random.rand(N, 1)
    v = v / np.linalg.norm(v, 1)
    M_hat = (d * M) + (((1 - d) / N) * np.ones((N, N)))
    for i in range(num_iterations):
        v = M_hat @ v
    return v

pr = pagerank(stochastic_matrix) # Compute the PageRank values

index_to_token = {i: token for i, token in enumerate(voc)} # Create a dictionary to map index to token

sorted_tokens = sorted(index_to_token.items(), key=lambda x: pr[x[0]], reverse=True) # Sort the tokens by their PageRank values

for i in range(10):  # Print the top 10 tokens and their PageRank values
    print(f"{sorted_tokens[i][1]}: {pr[sorted_tokens[i][0]][0]}")

security: 3.1359614855387134e-06
system: 2.3122636217874822e-06
software: 2.039313602769593e-06
information: 1.5352542405737604e-06
testing: 1.0693571188309863e-06
computer: 9.945621279230246e-07
application: 9.685429586986447e-07
datum: 9.362299914780435e-07
code: 9.20537476406246e-07
user: 8.939878351435672e-07


(3) (22 points) Extend the Jupyter notebook (in Python) created in 1) and 2) by providing solutions to the following tasks:
    
(a) (5 points) Create a copy (named e.g. “dice_matrix”) of the co-occurrence matrix obtained in 1c), calculate the significances of the co-occurrences using the Dice coefficient, and update the 
elements in “dice_matrix” accordingly.

In [11]:
dice_matrix = np.copy(coocc_matrix) # Make a copy of the co-occurrence matrix

for i in range(dice_matrix.shape[0]): # Calculate the Dice coefficients
    for j in range(dice_matrix.shape[1]):
       
        numerator = 2 * coocc_matrix[i,j]  # Calculate the numerator and denominator of the Dice coefficient
        denominator = np.sum(coocc_matrix[i,:]) + np.sum(coocc_matrix[:,j])
                
        if denominator != 0: # Calculate the Dice coefficient
            dice_coef = numerator / denominator
        else:
            dice_coef = 0
                
        dice_matrix[i,j] = dice_coef # Update the dice_matrix with the Dice coefficient

print("Co-occurrence matrix:\n", coocc_matrix) # Print the co-occurrence matrix and the Dice coefficient matrix
print("Dice coefficient matrix:\n", dice_matrix)

Co-occurrence matrix:
 [[436. 189. 178. ...   0.   0.   0.]
 [189. 166.  99. ...   0.   0.   0.]
 [178.  99. 176. ...   0.   0.   0.]
 ...
 [  0.   0.   0. ...   0.   1.   1.]
 [  0.   0.   0. ...   1.   0.   1.]
 [  0.   0.   0. ...   1.   1.   0.]]
Dice coefficient matrix:
 [[0.08141923 0.04271669 0.03825489 ... 0.         0.         0.        ]
 [0.04271669 0.04751002 0.02659503 ... 0.         0.         0.        ]
 [0.03825489 0.02659503 0.04454568 ... 0.         0.         0.        ]
 ...
 [0.         0.         0.         ... 0.         0.25       0.25      ]
 [0.         0.         0.         ... 0.25       0.         0.25      ]
 [0.         0.         0.         ... 0.25       0.25       0.        ]]


(b) (2 points) Output the Dice significance values of the co-occurrences ("software", "security") and ("security", "software"). These must match.

In [12]:
print(voc.index("software"))
print(voc.index("security"))

print(dice_matrix[0][1]) 
print(dice_matrix[1][0])
assert dice_matrix[0][1] == dice_matrix[1][0] # assert will raises an exception if the condition is not met 
                                                # Because this assert is not raising an execption hence “dice_matrix[i][j]” and “dice_matrix[j][i]” have the same values.

print(dice_matrix[voc.index("software")][voc.index("security")]) 
print(dice_matrix[voc.index("security")][voc.index("software")]) 
assert dice_matrix[voc.index("software")][voc.index("security")] == dice_matrix[voc.index("software")][voc.index("security")]

1
0
0.04271669115154255
0.04271669115154255
0.04271669115154255
0.04271669115154255


(c) (5 points) Now calculate the value of the cosine similarity between the context vectors of the tokens "software" and "security". You could do that by relying on Numpy’s functions “np.dot()” and “np.linalg.norm()” or by making use of the function “cosine_similarity()” from “sklearn.metrics.pairwise”. In the latter case, the vectors may have to be reshaped. 

Note: The context vector of a term i can be obtained by accessing the i-th row in “dice_matrix”. For instance, the context vector of the term “software” can be accessed by calling dice_matrix[voc.index("software")] .

In [13]:
software_context = dice_matrix[voc.index("software")] # Accessing the context vectors of "software" and "security"
security_context = dice_matrix[voc.index("security")]

cosine_sim = np.dot(software_context, security_context) / (np.linalg.norm(software_context) * np.linalg.norm(security_context)) # Calculating the cosine similarity between the context vectors

print("Cosine similarity between 'software' and 'security':", cosine_sim)

Cosine similarity between 'software' and 'security': 0.5525394550251929


In [14]:
from sklearn.metrics.pairwise import cosine_similarity

software_context = dice_matrix[voc.index("software")].reshape(1, -1) # Accessing the context vectors of "software" and "security" and reshaping them
security_context = dice_matrix[voc.index("security")].reshape(1, -1)

cosine_sim = cosine_similarity(software_context, security_context)[0][0] # Calculating the cosine similarity between the context vectors

print("Cosine similarity between 'software' and 'security':", cosine_sim)

Cosine similarity between 'software' and 'security': 0.5525394550251929


(d) (3 points) Compare the values obtained in 3b) and 3c). What do you notice? How do you interpret the different values? Formulate complete answer sentences and enter them in the Jupyter 
notebook

Answer: 

Here, question 3(b) computes the Dice significance values of the co-occurrences and shows that for two tokens its same irrespective of order of occurance. Similarly question 3(c) measures the calculate the value of the cosine similarity between the context vectors of the tokens "software" and "security". Dice significance value and cosine similarity are two distinct metrics for comparing the similarity of two collections of data, such as two sets of words in a corpus.

The question 3(b)'s Dice coefficient compares the size of two sets' intersection and union to determine how similar they are. The Dice coefficient in the context of text analysis can be used to compare two documents based on the overlap of their word sets or to compare two words based on their co-occurrence in a corpus.

In contrast, question 3(c)'s cosine similarity calculates the angle between two sets' respective vectors in a multidimensional space to determine how similar they are. The angle between two documents' respective vector representations in a high-dimensional vector space, such as a term frequency-inverse document frequency (TF-IDF) space, is frequently employed in the context of text analysis to quantify how similar two texts are.

Both the Dice coefficient and cosine similarity can be used to measure similarity between words based on their co-occurrence in a corpus. However, the Dice coefficient is based on the size of the intersection and union of the co-occurrence sets, while cosine similarity is based on the angle between the corresponding vector representations. Additionally, the Dice coefficient is a binary measure of similarity, indicating whether two words co-occur or not, while cosine similarity is a continuous measure of similarity, indicating the degree of similarity between the two vectors.

(e) (7 points) What are the 10 most similar words/tokens to “software” in descending order of their cosine similarity scores? For this purpose, calculate the cosine similarity values between the context vector of the token “software” and all row vectors in “dice_matrix”. Hint: The function "cosine_similarity()" from "sklearn.metrics.pairwise" can be passed this matrix as a single 
parameter. Note: the most similar token to “software” must be “software”.

In [15]:
software_context = dice_matrix[voc.index("software")].reshape(1, -1) # Accessing the context vector of "software" and reshaping it

similarity_scores = cosine_similarity(software_context, dice_matrix) # Calculating the cosine similarity between the context vector of "software" and all row vectors in "dice_matrix"

top10_similar_words = [voc[i] for i in np.argsort(similarity_scores[0])[::-1][:10]] # Sorting the scores in descending order and retrieving the top 10 words/tokens

print("The 10 most similar words/tokens to 'software' are:")
for i, word in enumerate(top10_similar_words):
    print(i+1, "-", word)

The 10 most similar words/tokens to 'software' are:
1 - software
2 - process
3 - development
4 - testing
5 - system
6 - security
7 - product
8 - requirement
9 - quality
10 - program
